# Generated by Django 2.0.5 on 2018-05-15 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='somevalue', max_length=250, null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestCase.Action')),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('locator', models.CharField(blank=True, default='locator_dflt', max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='example', max_length=250, null=True)),
                ('slug', models.SlugField(default='example', max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('deeplink', models.CharField(blank=True, default='deeplink_dflt', max_length=250, null=True)),
                ('Project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TestCase.Project' )),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('Smoke', 'Smoke'), ('General', 'General'), ('Detailed', 'Detailed')], default='Smoke', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('condition', models.ManyToManyField(to='TestCase.Condition')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TestCase.Project')),
                ('tag', models.ManyToManyField(to='TestCase.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TestStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='somevalue', max_length=250, null=True)),
                ('expresult', models.TextField()),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestCase.Condition')),
            ],
        ),
        migrations.AddField(
            model_name='testcase',
            name='teststep',
            field=models.ManyToManyField(to='TestCase.TestStep'),
        ),
        migrations.AddField(
            model_name='element',
            name='Project',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='TestCase.Project'),
        ),
        migrations.AddField(
            model_name='element',
            name='screen',
            field=models.ManyToManyField(to='TestCase.Screen'),
        ),
        migrations.AddField(
            model_name='condition',
            name='element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TestCase.Element'),
        ),
        migrations.AddField(
            model_name='condition',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestCase.Screen'),
        ),
        migrations.AddField(
            model_name='condition',
            name='testdata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TestCase.TestData'),
        ),
    ]
