# Generated by Django 2.0.5 on 2018-05-15 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestCase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='Project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TestCase.Project'),
        ),
        migrations.AlterField(
            model_name='screen',
            name='Project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TestCase.Project'),
        ),
    ]
