# Generated by Django 2.0.5 on 2018-05-08 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestCase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='element',
        ),
        migrations.RemoveField(
            model_name='action',
            name='testdata',
        ),
    ]
