# Generated by Django 2.0.5 on 2018-05-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestCase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='status',
            field=models.CharField(choices=[('Passed', 'Passed'), ('Failed', 'Failed'), ('To be checked', 'To be checked')], default='To be checked', max_length=30),
        ),
    ]
