# Generated by Django 2.0.5 on 2018-05-08 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestCase', '0002_auto_20180508_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TestCase.Element'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='testdata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TestCase.TestData'),
        ),
    ]
