# Generated by Django 2.0.5 on 2018-05-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestCase', '0003_auto_20180508_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='title',
            field=models.CharField(blank=True, default='somevalue', max_length=250, null=True),
        ),
    ]
