# Generated by Django 2.0.5 on 2018-05-15 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestCase', '0003_condition_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='teststep',
            name='Project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TestCase.Project'),
        ),
    ]
