# Generated by Django 2.0.5 on 2018-05-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestCase', '0004_auto_20180508_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teststep',
            name='title',
            field=models.CharField(blank=True, default='somevalue', max_length=250, null=True),
        ),
    ]
