# Generated by Django 2.0.5 on 2018-05-10 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestCase', '0005_auto_20180508_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='example', max_length=250, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='testcase',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TestCase.Project'),
        ),
    ]
