# Generated by Django 2.0.5 on 2018-05-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestCase', '0006_auto_20180510_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default='example', max_length=250, unique=True),
        ),
    ]
